def main():
    f = open("microcode.txt", "r")
    out = open("microcode.h", "w")
    out.write("#pragma once\n\n")
    out.write("// AUTOGENERATED - DO NOT MODIFY UNLESS YOU KNOW WHAT YOU'RE DOING (YOU DON'T)\n")
    out.write("#include <cstdint>\n\nconstexpr uint32_t ucode[] = {\n")
    num = 0
    for line in f:
        if (len(line) < 25):
            out.write("\t0b000000000000000000000, // " + hex(num) + "\n")
            num += 1
            continue
        out.write('\t0b')
        for i in range(4, 25):
            if (line[i] == ' '):
                out.write('0')
            else:
                out.write('1')
        out.write(", // " + hex(num) + "\n")
        num += 1
    out.write('};\n')
        
main()